### ISSUE TITLE
“_wrappers.so” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by mikeyward** [danielecook/gist-alfred#16]
I tried manually adding `_wrappers.so` within the package to Gatekeeper using `spctl`, but no dice. Any ideas?

<img width="532" alt="Screen Shot 2020-07-18 at 6 56 19 PM" src="https://user-images.githubusercontent.com/1214535/87863370-5f1f8f00-c928-11ea-9081-d8895379ac65.png">

**Comment by petebocken** [comment]
@wookiee Guessing you figured this out by now, but for anyone else. You have to go into System Preferences > Security & Privacy > General and click "Allow Anyway" under the "Allow apps downloaded from:" section.

https://p110.p2.n0.cdn.getcloudapp.com/items/xQuYyEoq/e22a8d74-d774-4b75-9576-7fb43a21673f.png

**Comment by danielecook** [comment]
Thanks @petebocken!
