### ISSUE TITLE
is it possible to see the code of the gist at the right side of the window? like the snippets in Alfred?

### ISSUE THREAD

**Issue by ctwhome** [danielecook/gist-alfred#17]
![image](https://user-images.githubusercontent.com/4195550/114302755-becb5500-9aca-11eb-847b-2de54d5d92c3.png)

**Comment by danielecook** [comment]
@ctwhome unfortunately not that I know of. That would be pretty nice - I wonder whether there is a way to dynamically load snippets in Alfred.
