### ISSUE TITLE
[feature request] command modifier key to go to web version of the gist

### ISSUE THREAD

**Issue by nikivdev** [danielecook/gist-alfred#3]
Would be really nice to have a command key modifier that when pressed will allow to go to the gist in the browser.

Thank you and I hope you will consider adding this. Thank you for a great workflow.

**Comment by danielecook** [comment]
Don't have time to do that now but happy to take Pull Requests! Maybe if I get a chance later this summer.

**Comment by danielecook** [comment]
Resolved with cca2435aa24d2645dafc609d922df9a15fd0c7e0
