### ISSUE TITLE
Can you please add an option to get gists's url to clipboard

### ISSUE THREAD

**Issue by nikivdev** [danielecook/gist-alfred#5]
I press ctrl key or cmd key and the link to the url is given to user, not the content of the gist.

**Comment by danielecook** [comment]
I may be able to look at this this weekend. I saw that you use snippets lab. I have it also - how often does it crash for you?

**Comment by nikivdev** [comment]
Never actually. Now I think I am lucky. 🙂

**Comment by danielecook** [comment]
All set:

https://github.com/danielecook/gist-alfred/releases/tag/v0.3

Use <kbd>alt</kdb>

**Comment by nikivdev** [comment]
Thank you. 💚
