### ISSUE TITLE
How do I update Gist Library?

### ISSUE THREAD

**Issue by nikivdev** [danielecook/gist-alfred#6]
For example I have starred a gist. But it won't show up in the Gists Alfred workflow under starred.

How does the updating of the library work?

There is a reload action there : 

![2017-01-16 at 13 35](https://cloud.githubusercontent.com/assets/6391776/21983251/a46de206-dbf0-11e6-9259-7491bc30fd39.png)

But I am not really sure what that does as all it shows is some arbitrary gists.

Thank you for any help.

**Comment by danielecook** [comment]
Did you use gg_src first?

**Comment by nikivdev** [comment]
I don't have gg_src I believe : 

![2017-01-16 at 17 06](https://cloud.githubusercontent.com/assets/6391776/21990163/10a0c386-dc0e-11e6-834f-d7bf4b72488a.png)

**Comment by danielecook** [comment]
Ah sorry I meant gg_set. Use gg_set!

**Comment by nikivdev** [comment]
For some reason gg_set doesn't work for me. 

I inputted my username. I inputted my token once again. I still get these options and nothing else : 

![2017-01-16 at 17 18](https://cloud.githubusercontent.com/assets/6391776/21990601/c2db75ae-dc0f-11e6-8e37-b2f6d62a7b2a.png)

**Comment by nikivdev** [comment]
I think this is a bug, since if user is authorised already, it should say so.

**Comment by nikivdev** [comment]
I have however did the 'Reload' command, waited for a bit. I think it still doesn't get all my starred gists. For example : 

![2017-01-16 at 17 23](https://cloud.githubusercontent.com/assets/6391776/21990854/a069ccb8-dc10-11e6-847e-10d8f42dc625.png)

It doesn't find it at all. Also the 'latest version..' is a duplicate although I believe I starred it once.

**Comment by danielecook** [comment]
This might be fixed.

https://github.com/danielecook/gist-alfred/releases/tag/0.4

I can't figure out why the one record is duplicated. If a gist has multiple files though they will both show up. Also, privately starred gists that you don't own will not be listed there.

**Comment by danielecook** [comment]
@nikitavoloboev please try the latest version. Updating is straightforward.
