### ISSUE TITLE
Needs update for macos

### ISSUE THREAD

**Issue by wizalexander** [danielecook/gist-alfred#9]
Alfred has updated to allow compatibility with High Sierra. This breaks your workflow.

**Comment by danielecook** [comment]
Thanks I will take a look.

**Comment by danielecook** [comment]
I'm not having any problems - can you provide me with some additional debug info? What error are you seeing?

**Comment by GabLeRoux** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/1264761/39847771-5521af66-53d1-11e8-923a-8541cf26d70e.png)

https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

* danielecook/gist-alfred version `0.4` 
* MacOS Sierra 10.13.4 (17E202). 
* Alfred 3.6.1

**Comment by danielecook** [comment]
@GabLeRoux Please try the latest version...

**Comment by GabLeRoux** [comment]
Original problem seems solved 👍 

![image](https://user-images.githubusercontent.com/1264761/40842680-ac6d1f50-657c-11e8-8c34-c8021bb9990a.png)

I'm getting a new error message tho, I just created #11

**Comment by danielecook** [comment]
Please give the latest update a try @GabLeRoux

**Comment by GabLeRoux** [comment]
I got one step further:

![image](https://user-images.githubusercontent.com/1264761/40848210-888f52b4-658c-11e8-9352-3278beb50558.png)

failed with #8

![image](https://user-images.githubusercontent.com/1264761/40848202-814ba066-658c-11e8-84bb-9e3c0d0f2c52.png)


After running `update gists`, it managed to work tho 🎉 

![image](https://user-images.githubusercontent.com/1264761/40848239-9b5519ba-658c-11e8-9ae7-abecfdf358f0.png)

![image](https://user-images.githubusercontent.com/1264761/40848313-d4ed88ec-658c-11e8-9d08-a5c8fb9df12e.png)

Good job 🤘

**Comment by danielecook** [comment]
Thank you I hope this helps you be more productive!
